#!/usr/bin/env bash

gcc -o keygen keygen.c -O2 -march=native
strip keygen
gcc -o otp_enc otp_enc.c -O2 -march=native
strip otp_enc
gcc -o otp_enc_d otp_enc_d.c -O2 -march=native
strip otp_enc_d
gcc -o otp_dec otp_dec.c -O2 -march=native
strip otp_dec
gcc -o otp_dec_d otp_dec_d.c -O2 -march=native
strip otp_dec_d
